Ready for review
noomdalv/Using-Bootstrap pull request #1
Opened 2019-08-22 22:49 UTC by noomdalv

2019-08-23 01:04 UTC, stratospherique reviewed
### Pull request under the review by Ahmed Mahfoudh (TSE)

2019-08-23 01:37 UTC, stratospherique requested changes
## Hi @noomdalv , Great work. However, some requirements needs to be implemented in order for us to approve your project:

##### Featured story
- In that section, you have some text that sits on top of it. Please remove
![image](https://user-images.githubusercontent.com/26124023/63560582-773b3280-c54e-11e9-862f-165fbf7e7f69.png)

### footer ( also subscribe and newsletter )

- Your are using responsive layout there. However font size and some of the elements is not responsive.

#### Implementation details

* [ ] add the bootstrap [viewport metatag](https://getbootstrap.com/docs/4.3/getting-started/introduction/#responsive-meta-tag)
* [ ] It uses Bootstrap Css classes for styling ( for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options) )

### General notes:

* [ ] The project has to have a descriptive README.md

2019-08-23 01:37 UTC, stratospherique commented on index.css
> +@media (max-width: 768px) {
You can use Bootstrap default classes for responsiveness.

2019-08-23 01:39 UTC, stratospherique commented
### And that's it. When finished implementing the above, kindly resubmit another code review. 
#### Keep up the good work :muscle: :muscle:

2019-09-05 16:45 UTC, noomdalv commented
PROJECT READY

1. Bootstrap metatag implemented

2. Responsiveness added for:
Navbar List
Subscribe section
Newsletter section
Footer

3. Project README updated

2019-09-05 18:39 UTC, stratospherique requested changes
### Great work :clap: :clap: . Unfortunately, you missed the most important goal of this project. **You should be using Bootstrap default classes** for responsive positioning and layout. :disappointed: 

* [ ] You should use Bootstrap Css classes **everywhere** for styling ( for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options) )

* [ ] **You should add linter configuration :no_entry_sign:  It's mandatory. You could check Microverse's [repo](https://github.com/microverseinc/linters-config/tree/master/css), it will walk through the process of the configuration**.

#### Please take care of this important matter :pray: . When finished, submit another code review request

2019-09-05 18:39 UTC, stratospherique commented on index.css
> +
- Again these media queries are necessary. You supposed to use bootstrap classes.

2019-09-09 22:24 UTC, noomdalv commented
Stickler added, linter warnings such as (fallback-colors) and selectors (no-descending-specificity) errors not possible to be corrected with fixer enabled so ignore those.

Classes for bootstrap are implemented throught the whole project, most of the positioning was done using bootstrap flex properties, please review project before giving any non true suggestions, thanks

2019-09-10 00:36 UTC, uche-inyama reviewed
## Hi there, great job so far :fire: 
Kindly ensure that this project passes the linter checks.

### When you are done, submit another form for code review.

2019-09-10 22:54 UTC, noomdalv commented
Stickler errors fixed, project finished.

2019-09-10 22:57 UTC, stratospherique approved these changes
### Great Work :clap: . All requirements are met :100: . Your project is approved :+1: :+1: :+1:  and you can merge to master. Keep up the good work :muscle:

2019-09-10 23:04 UTC, merged